Add input clear button background instruction
eclipsesource/jsonforms2-website pull request #126
Opened 2020-11-06 13:28 UTC by TheZoker

Add instructions on how to customize the background color of the input clear button

2020-12-01 10:25 UTC, sdirix commented on src/pages/docs/controls.mdx
> +If you want to customize the background of the input clear button (the one you can see, if you hover of the input field), you can need to wrap you `JsonForms` component in an `ThemeProvider` componen
```suggestion
The background of the the 'clear input button' (the one you can see when you hover of the input field) is by default your theme's `palette.background.default` color. If you want to customize only the background of this button you can use the custom theme variable `jsonforms.input.delete.background`.
```

2020-12-01 10:33 UTC, sdirix commented on src/pages/docs/controls.mdx
> +
```suggestion
## Theming
```

2020-12-01 10:33 UTC, sdirix commented on src/pages/docs/controls.mdx
> +### Use custom theme to change input clear background
```suggestion
### Customize 'clear input button' background
```

2020-12-03 10:54 UTC, sdirix requested changes
Please update the PR. Can you post a screenshot of how the background color looks like with the latest JSON Forms?

2020-12-08 15:44 UTC, TheZoker commented
This is what the button looks within the docs:
![image](https://user-images.githubusercontent.com/1368405/101505135-4e71c300-3974-11eb-8b3e-e26c4b62134e.png)

And this is the default:
![image](https://user-images.githubusercontent.com/1368405/101505435-a3add480-3974-11eb-88d6-641bed6c9936.png)

2020-12-16 16:08 UTC, merged