Enhance page titles for SEO
eclipsesource/jsonforms2-website pull request #194
Opened 2021-07-08 10:34 UTC by TheZoker

- Uses `-` as page title separator
- Fix support page title
- Add "Example" to page title (within examples)
- Remove unnecessary `controls.js` file
- Rename `layoutexample.mdx` to `layout.mdx` since it is already in the example folder
- Add blog title, although it does not seem to make any difference (https://github.com/facebook/docusaurus/discussions/5119)

Closes #193

2021-07-08 13:44 UTC, sdirix requested changes
I like it! Only minor comments

2021-07-08 13:44 UTC, sdirix commented on content/pages/index.js
> +      title={siteConfig.tagline}
What does this change do exactly?

2021-07-08 13:44 UTC, sdirix commented on content/docs/uischema/controls.mdx
> +description: Controls represent the basic building blocks for creating forms
```suggestion
description: Controls generally represent properties declared in JSON Schema and serve to manipulate data.
```

2021-07-08 13:57 UTC, TheZoker commented on content/pages/index.js
> +      title={siteConfig.tagline}
The page title is now `More forms. Less code. - JSON Forms` instead of `JSON Forms | JSON Forms`

2021-07-30 16:35 UTC, sdirix approved these changes

2021-07-30 16:36 UTC, merged