Add Vue2 Vuetify Renderer Set
eclipsesource/jsonforms2-website pull request #227
Opened 2022-05-02 15:14 UTC by TheZoker

Add Vue2 Vuetify Renderer Set

Closes #209

2022-07-04 15:40 UTC, sdirix commented on content/docs/renderer-sets.mdx
> +It's not part of the core, but lives in it's own repository:
```suggestion
It's not part of the main repository, but lives in its own repository:
```

2022-07-04 15:48 UTC, sdirix requested changes
Vue2-Vuetify is missing a custom renderer box ;)

2022-07-04 16:00 UTC, sdirix requested changes
A mention of vue2 vuetify is missing in the architecture doc

2022-12-01 13:41 UTC, lucas-koehler commented
@sdirix Can we merge this to conclude the website updates for the 3.0 release?

2022-12-01 13:45 UTC, sdirix approved these changes

2022-12-01 13:46 UTC, merged