add FAQ Section for multipleOf
eclipsesource/jsonforms2-website pull request #239
Opened 2022-08-31 07:45 UTC by LukasBoll

closes #221

Signed-off-by: Lukas Boll lukas-bool@web.de

2022-09-22 14:37 UTC, lucas-koehler requested changes
Hey, thanks for the documentation. Looks already pretty good to me execpt for some minor issues (see inline comments) :)

2022-09-22 14:37 UTC, lucas-koehler commented on content/faq/faq.mdx
> +JSON Forms uses AJV for the validation of data. By default, the `multipleOf` option of AJV only works with integers. If you are using fractional dividers, you also need to set the `multipleOfPrecisio
Please use a new line for each sentence. This makes it easier to diff changes in the future :)

2022-09-22 14:37 UTC, lucas-koehler commented on content/faq/faq.mdx
> +In the Following example `multipleOf` is set to 0.1 and `multipleOfPrecision` is set to 2.
```suggestion
In the following example `multipleOf` is set to `0.1` and `multipleOfPrecision` is set to `2`.
```

2022-09-22 14:37 UTC, lucas-koehler commented on content/faq/faq.mdx
> +    …
I would remove this line

2022-09-22 14:37 UTC, lucas-koehler commented on content/faq/faq.mdx
> +    …
I would remove this line

2022-09-22 14:37 UTC, lucas-koehler commented on content/faq/faq.mdx
> +const [ajvInstance] = useState<Ajv>(createAjv({multipleOfPrecision:2}));
```suggestion
const [ajvInstance] = useState<Ajv>(createAjv({ multipleOfPrecision: 2 }));
```

2022-09-22 14:37 UTC, lucas-koehler commented on content/faq/faq.mdx
> +## How can I use multipleOf with values smaller 1?
```suggestion
## How can I use multipleOf with values smaller than 1?
```

2022-10-03 11:50 UTC, LukasBoll commented
Thanks for the review, I updated the pull request according to your suggestions.

2022-10-04 07:59 UTC, lucas-koehler approved these changes
Thanks for the updates. LGTM now!

2022-10-04 07:59 UTC, merged