update to JSON Forms 3.0.0
eclipsesource/jsonforms2-website pull request #240
Opened 2022-09-23 08:40 UTC by LukasBoll

Signed-off-by: Lukas Boll lukas-bool@web.de

2022-09-23 10:24 UTC, lucas-koehler requested changes
The styling seems to be broken for the new api. See the following screenshot showing the new core api on the left and the current website on the right:
![image](https://user-images.githubusercontent.com/6959840/191941140-338724f2-fdde-4bf1-b168-eeecf4f6e779.png)

It is suspicious that the PR deletes many `main.css` files, e.g. [static/api/core/assets/css/main.css](https://github.com/eclipsesource/jsonforms2-website/pull/240/files#diff-8a6f0337e722ffdf6a265a79dd5c0edce56ce8b2ed27379457ca91c2320c475e)

Maybe something went wrong during api generation or copying?

2022-09-23 10:24 UTC, lucas-koehler commented on src/components/common/Demo.js
> +import get from 'lodash/get';
As I see it, this is not used in this file. Can we remove it?

2022-09-23 10:24 UTC, lucas-koehler commented on src/components/examples/Categorization.js
> +    label: "Address",
```suggestion
    label: 'Address',
```

2022-09-27 08:11 UTC, LukasBoll commented
Thanks for the review. I think the css classes are not deleted, but the css files are collapsed into one line. The styling is working on the [deploy preview](https://deploy-preview-240--jsonforms.netlify.app/api/core/index.html). I checked the styling local again: When running `npm run start` everything worked for me, while running `npm run serve` was leading to the results you mentioned.

2022-09-27 12:37 UTC, lucas-koehler requested changes
Hi @LukasBoll , thanks for the update and the explanation. The behavior is fine with me as you explained. Maybe the serve just behaves strangely.
However, I noticed one more issue with the new page: The title of the new API pages is only `'JSON'` now. See this screenshot of the core API (the problem is also present for other APIs)
![image](https://user-images.githubusercontent.com/6959840/192528198-fd682bfe-5f38-434d-9969-50538c98f9ff.png)

2022-09-29 10:00 UTC, lucas-koehler approved these changes
Approved because fixing the API page titles will be fixed in follow up issue #241

2022-09-29 10:01 UTC, merged