add dynamic enum Tutorial
eclipsesource/jsonforms2-website pull request #278
Opened 2023-10-09 11:55 UTC by LukasBoll

closes #270

2024-02-19 16:58 UTC, sdirix reviewed
I like it!

Please add a small section at the end that this behavior can be generalized and extracted into React HOCs for cleaner code.

2024-02-19 16:58 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +To address those requirements, we'll create custom renderers for the country and region.
```suggestion
To address those requirements, we'll create custom renderers for country and region.
```

2024-02-19 16:58 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +The example is also implemented in the [react-seed](https://github.com/eclipsesource/jsonforms-react-seed) app.
```suggestion
```

2024-02-19 16:58 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +Both `country` and `region` have a property `endpoint`, indicating the endpoint from which the data should be fetched.
```suggestion
Both `country` and `region` have a property `x-endpoint`, indicating the endpoint from which the data should be fetched.
```

2024-02-19 16:58 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +}
We need to use the context in the JSX somewhere

2024-02-19 16:58 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +The core of the country renderer is a dropdown, we can reuse the MaterialEnumControl from the material-renderer set.
```suggestion
The core of the country renderer is a dropdown, therefore we can reuse the MaterialEnumControl from the React Material renderer set.
```

2024-02-19 16:58 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +Since these fields are not part of the standard JSON schema type in JSON Forms, we must add them to the schema´s interface and access them as follows:
```suggestion
Since these fields are not part of the standard JSON schema type in JSON Forms, we must add them to the schema's interface and access them as follows:
```

2024-02-19 16:58 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +We utilize the `useEffect` hook to reload new options, if API changes.
```suggestion
We utilize the `useEffect` hook to initialize the options.
```

2024-02-19 16:58 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +  }, [api, endpoint]);
```suggestion
  useEffect(() => {
    api.get(endpoint).then((result) => {
      setOptions(result);
    });
  }, []);
```

2024-03-04 15:44 UTC, LukasBoll commented on content/docs/tutorial/dynamic-enum.mdx
> +}
Thanks, I added your suggestions. The context is used in the country and region renderer, but I also added an example on how to access the context right below this chapter.

2024-03-04 15:50 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +}
Ah I see, you're relying on the default context and skip the
```tsx
const APIService = new API(url);
// ...
<APIContext.Provider value={APIService}>
  <JsonForms />
</APIContext.Provider />
```

2024-03-20 09:36 UTC, sdirix requested changes, later dismissed

2024-03-20 09:36 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +A running example of the scenario can also be seen at the [react-seed](https://github.com/eclipsesource/jsonforms-react-seed) app.
```suggestion
```

2024-03-20 09:36 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +```
Please add the wrapping code for the renderers, i.e. `withJsonFormsControlProps` etc. here and in the other listings.

2024-03-20 09:36 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +export const Country = (
let's not export the raw renderers
```suggestion
const CountryControl = (
```

2024-03-20 09:36 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +React Context allows you to share data globally within your application, enabling components deep in the component tree to access data without needing to pass properties through all parent elements.
Link to the official react context documentation of react

```suggestion
React Context allows you to share data deep in the component tree to access data without needing to pass additional properties through the component hierarchy.
```

2024-03-20 09:36 UTC, sdirix commented on content/docs/tutorial/dynamic-enum.mdx
> +Changing the context's value will trigger a re-render of components that use it, making it a powerful tool for managing dynamic data.
```suggestion
Changing the context's value will trigger a re-render of components that use it.
```

2024-04-15 15:34 UTC, LukasBoll commented
thank you, I applied the changes from your review!

2025-10-24 14:31 UTC, lucas-koehler approved these changes
Looked pretty good to me already. I did a few minor fixes regarding wording and using `x-` prefixed schema properties for endpoint and dependents.

2025-10-24 14:34 UTC, merged