Add FAQ: update a field depending on another field
eclipsesource/jsonforms2-website pull request #281
Opened 2023-11-13 12:35 UTC by LukasBoll

Add FAQ section: How to update a field depending on another field closes #269

2024-02-19 16:38 UTC, sdirix requested changes
Please add the middleware approach as approach number 1. In that approach mention that the similar approach 2 can be used for JSON Forms before version X without middleware support.

2024-02-19 16:38 UTC, sdirix commented on content/faq/faq.mdx
> +It's important to only create a new object when necessary to avoid infinite loops.
This sentence should be in a warning element. We already have some in the website.

2024-02-19 16:38 UTC, sdirix commented on content/faq/faq.mdx
> +The onChange method triggers whenever a user changes the form data.
Mention that this approach should only be used when using an older JSON Forms without middleware support as it works in a similar way, however the middleware variant is more performant.

2024-03-20 12:40 UTC, sdirix commented
Please resolve the conflicts by cherry-picking the lastest commit on `master`

2024-04-10 07:39 UTC, sdirix commented on content/faq/faq.mdx
> +Its more performant to use the middlewear approach, but this is a good approach for JSON Forms before version v3.2.0
```suggestion
It's more performant to use the middleware approach, but this is a good approach for JSON Forms before version v3.2.0
```

2024-04-10 07:40 UTC, sdirix commented on content/faq/faq.mdx
> +import { INIT, UPDATE_DATA } from  '@jsonforms/core'
```suggestion
import { INIT, UPDATE_CORE, UPDATE_DATA } from  '@jsonforms/core'
```

2024-04-10 07:41 UTC, sdirix commented on content/faq/faq.mdx
> +    }else{
```suggestion
    } else {
```

2024-04-10 07:42 UTC, sdirix approved these changes

2024-04-11 09:58 UTC, lucas-koehler commented
@sdirix Can we merge this or is there a reason it is approved but not merged?

2024-04-11 09:59 UTC, sdirix commented
We can merge, I just did a few minor changes and waited for the build to complete.

2024-04-11 10:16 UTC, merged