WIP Release 3.2.0
eclipsesource/jsonforms2-website pull request #289
Opened 2024-01-23 09:45 UTC by lucas-koehler

- Update architecture diagrams
- add release news entry
- fix broken links
- remove vue 2
- updated api docs

2024-01-23 09:51 UTC, lucas-koehler commented
When reviewing, please pay special attention to the suggested news entry. Also consider that the news date is embedded in the file name (currently 24.01.). We might need to update this depending on the concrete release day :D

2024-01-23 15:39 UTC, sdirix requested changes
Looks good!

We should add the following changes:
 - Adapt the news on the landing page too (it's hard coded there atm)
 - In the news link to the changelog in the repository
 - Update the used JSON Forms version of the website to 3.2.0

2024-01-23 15:39 UTC, sdirix commented on content/docs/integrations/vue.mdx
> +For Vue we provide a HTML5 based renderer set, `@jsonforms/vue-vanilla` for Vue 3.
We should also mention vue vuetify which is in a preview state

2024-01-23 15:39 UTC, sdirix commented on content/docs/renderer-sets.mdx
> +The Vue Vuetify Set provides a Vuetify based renderer set for JSON Forms.
We should explain that Vue Vuetify is in a preview state and has some known bugs. We are looking for contributors to fix them. We can use a "Note" for this.

2024-01-23 17:17 UTC, lucas-koehler commented
@sdirix thanks for the review, I adapted the mentioned points.

2024-01-24 09:16 UTC, lucas-koehler commented
@sdirix I updated the renderer set feature table and removed some more vue 2 references i found. Hopefully, everything is cleaned up now :)

2024-01-24 09:32 UTC, sdirix commented
@lucas-koehler I just saw that we seemingly have a regression? For some reason some of the inputs in the landing page form are using an outlined input

2024-01-24 11:07 UTC, sdirix approved these changes
Looks good to me, only minor comments

2024-01-24 11:07 UTC, sdirix commented on content/news/2024-01-24-jsonforms-3-2-0.md
> +We welcome any feedback of curious users. Any questions? Check out our [community forum](http://jsonforms.discourse.group).
```suggestion
We released v3.2.0 🎉. Besides various fixes and improved developer tooling, this release adds middleware support to all bindings. This makes it a breeze to hook into data updates!

With this release, the Angular bindings and Angular Material renderer set now support Angular 16 and 17. Special thanks to [JBBianchi](https://github.com/JBBianchi) for contributing this massive upgrade.

You can find the full changelog in the [Github release](https://github.com/eclipsesource/jsonforms/releases/tag/v3.2.0).

We welcome any feedback of curious users. Any questions? Check out our [community forum](http://jsonforms.discourse.group).
```

2024-01-24 11:07 UTC, sdirix commented on content/pages/index.js
> +                With this release, the Angular core and material renderer set finally are up to date again supporting Angular 16 and 17. Special thanks to <a href="https://github.com/JBBianchi">JBBia
```suggestion
                With this release, the Angular bindings and Angular Material renderer set now support Angular 16 and 17. Special thanks to <a href="https://github.com/JBBianchi">JBBianchi</a> for contributing this massive upgrade.
```

2024-01-24 11:07 UTC, sdirix commented on content/pages/index.js
> +                We welcome any feedback of curious users. Any questions? Check out our <a href="http://jsonforms.discourse.group">community forum</a>.
```suggestion
                We welcome any feedback of curious users. Any questions? Check out our <a href="http://jsonforms.discourse.group">community forum</a>. See also our <a href="https://github.com/eclipsesource/jsonforms/blob/master/MIGRATION.md">migration guide</a>.
```

2024-01-24 11:36 UTC, merged