docs: fix broken link in what-is-jsonforms page
eclipsesource/jsonforms2-website pull request #305
Opened 2024-12-10 11:57 UTC by AssekoudaSamtou

When you hover and click the `Getting started` link at the end of the [documentation homepage](https://jsonforms.io/docs) (Figure 1), it takes you to 404-page `https://jsonforms.io/getting-started` (Figure 2).

![image](https://github.com/user-attachments/assets/ed051844-ab90-4d94-bdf2-144e52f12cd4)
Figure 1

![image](https://github.com/user-attachments/assets/228aeab8-99f4-4603-8247-a57f3620c072)
Figure 2

2024-12-10 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eclipsesource/jsonforms2-website?pullRequest=305) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/eclipsesource/jsonforms2-website?pullRequest=305) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eclipsesource/jsonforms2-website?pullRequest=305) it.</sub>

2024-12-10 12:31 UTC, sdirix requested changes
Hi @AssekoudaSamtou, thanks for the contribution :heart: 

However the issue is not in the link itself. The issue comes from the top nav bar not appending the trailing slash, e.g. when you append the trailing slash yourself in the Browser or click on "What is JSON Forms?" then the link works.

I think we need to adjust these `to` entries [here](https://github.com/eclipsesource/jsonforms2-website/blob/c8e7bf5348e99716e7a299ed49fd12629def736a/docusaurus.config.js#L45) to specify a trailing slash

2025-01-13 11:39 UTC, sdirix commented
Fixed with https://github.com/eclipsesource/jsonforms2-website/commit/eebccfa0081ceb365978531a251d6a1ba72cf956

2025-01-13 11:39 UTC, closed without merging

2025-01-13 16:46 UTC, AssekoudaSamtou commented
Hello @sdirix, thank you for looking into the issue and giving me more details. Happy you fixed it 😊