Restore providing-uischemas page
eclipsesource/jsonforms2-website pull request #68
Opened 2019-08-27 15:35 UTC by TheZoker

Restore providing-uischemas page from:
https://github.com/eclipsesource/jsonforms2-website/blob/old/src/pages/docs/ProvidingUISchemas.js

Fixes https://github.com/eclipsesource/jsonforms/issues/1372

2019-08-27 15:36 UTC, TheZoker commented
@sdirix

2019-08-29 09:06 UTC, sdirix requested changes
Looking at this change I noticed that 60% of this document was migrated to the currently provided `available-actions` page. I think it would be a good idea to move the remaining example to the same section, however the code needs to be updated.

2019-08-29 13:14 UTC, sdirix requested changes
Looks good in general. Please check the comments for change requests.

2019-08-29 13:14 UTC, sdirix commented on src/pages/docs/actions.mdx
> +                    <JsonForms
This is now called `JsonFormsDispatch`

2019-08-29 13:14 UTC, sdirix commented on src/pages/docs/actions.mdx
> +## `findUISchema(uischemas: object[], schema: JsonSchema, schemaPath: string, path: string, fallbackLayoutType?: string, control?: ControlElement, rootSchema?: JsonSchema)`
This should not be an own section but still be a part of the previous section. This is just a utility function and not one of the available actions.

2019-08-29 13:14 UTC, sdirix commented on src/pages/docs/actions.mdx
> +This function needs the uischemas (which consists of a tester and a uischema), the schema, the schemaPath and a subpath. Optionals parameters are a fallbackLayoutType (`VerticalLayout`by default), a
Would be nice if you could unify the spelling of uischema to `UI schema` in the whole page to be (mostly) consistent to the rest of the website.

2019-08-29 13:14 UTC, sdirix commented on src/pages/docs/actions.mdx
> +This function needs the uischemas (which consists of a tester and a uischema), the schema, the schemaPath and a subpath. Optionals parameters are a fallbackLayoutType (`VerticalLayout`by default), a
We should change `fallbackLayoutType` to `fallback layout type`

2019-08-29 13:14 UTC, sdirix commented on src/pages/docs/actions.mdx
> +This function needs the uischemas (which consists of a tester and a uischema), the schema, the schemaPath and a subpath. Optionals parameters are a fallbackLayoutType (`VerticalLayout`by default), a
We should change `a rootSchema` to `the root schema`

2019-08-29 13:24 UTC, TheZoker commented
I implemented the requested changes

2019-08-29 13:46 UTC, sdirix approved these changes

2019-08-29 13:46 UTC, merged

2019-08-29 13:46 UTC, sdirix commented
Thanks!