Add elementLabelProp
eclipsesource/jsonforms2-website pull request #79
Opened 2019-11-28 14:42 UTC by TheZoker

Fixes #77

2019-11-28 16:10 UTC, sdirix requested changes

2019-11-28 16:10 UTC, sdirix commented on src/pages/docs/controls.mdx
> +This option allows to set an element to be the main label the each array item. The value can be provided as a string or an array. More information can be found here:
```suggestion
This option allows to set a property to serve as a label for each array item. The `elementLabelProp` can be provided as a string or an array. More information can be found here:
```

2019-11-28 16:10 UTC, sdirix commented on src/pages/docs/controls.mdx
> +
Add a codeblock with an example
```suggestion
options: {
  elementLabelProp: "propertyName"
}
```

2019-11-28 16:10 UTC, sdirix commented on src/pages/docs/controls.mdx
> +In the following example the name will be shown instead of the message, because we provide the name prop.
```suggestion
In the following example each element will be labeled with its name instead of its message because we provide the name prop.
```

2019-11-29 11:09 UTC, TheZoker commented
Done

2019-11-29 12:18 UTC, sdirix approved these changes
LGTM

2019-11-29 12:19 UTC, merged